version: '3.0'

services:
  main:
    container_name: EducationMain
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 7890:7890
    command: npm run dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: Educationpostgres
    image: postgres:15
#    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5433
    command:
    - "postgres"
    - "-c"
    - "port=5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always


volumes:
  pgdata:
