version: '3.0'

networks:
  backend_network:
    external: true


services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8100:8100
      - 9229:9229
    command: npm run dev
    depends_on:
      - postgres
    restart: always
    networks:
      - backend_network

  postgres:
    container_name: postgres
    image: postgres:15
#    image: postgres:15-alpine
    env_file:
      - .docker.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - backend_network


volumes:
  pgdata: