version: '3.0'

services:
  main:
    container_name: chatmain
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8888:8888
    command: npm run start
    depends_on:
      - altynmessangerpostgres
    restart: always

  postgres:
    container_name: altynmessangerpostgres
    image: postgres:15
#    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always


volumes:
  pgdata:
